// @ts-ignore
import process from "process";
// @ts-ignore
import path from "path";
// @ts-ignore
import fs from "fs";
class Matcher {
    static getClassName(str, skipScriptClass = true) {
        let className = str.match(/class\s+(\w+)\s*:\s*public\s+(\w+)\s*{/); // 匹配class名(带继承)
        if (!className) {
            className = str.match(/class\s+(\w+)\s*{/); // 匹配class名(不带继承)
            if (!className) {
                return null;
            }
        }
        className.shift(); // 移除第一个元素
        for (let i = 0; i < className.length; i++) {
            const class_ = className[i];
            if (class_ == "ScriptClass" && skipScriptClass) {
                className.splice(i, 1); // 移除ScriptClass
                continue;
            }
        }
        let extends_ = [];
        if (className.length > 1) {
            extends_.push({
                class_: className[1],
                fixedClass_: className[1].replace(/API/, ""),
            });
        }
        return {
            class_: className[0],
            fixedClass_: className[0].replace(/API/, ""),
            extendsClass: extends_ || [],
        };
    }
    static getFunctions(str) {
        const Function = /(static\s+)?METHODS\((\w+)\);/g;
        let result = [];
        let tmp;
        while ((tmp = Function.exec(str))) {
            result.push({
                name: tmp[2],
                isStatic: tmp[1] && tmp[1] == "static ",
            });
        }
        return result;
    }
    static getClassDefine(str) {
        let classDefine = str.match(/static ClassDefine<([^>]+)> builder;/);
        if (classDefine) {
            return {
                class_: classDefine[1],
                fixedClass_: classDefine[1].replace(/API/, ""),
            };
        }
        return null;
    }
}
class Generator {
    static collectClassInfo(code) {
        let result = {
            class_: "",
            fixedClass_: "",
            extendsClass: [],
            methods: [],
            classDefine: {
                class_: "",
                fixedClass_: "",
            },
        };
        const class_ = Matcher.getClassName(code);
        if (!class_) {
            return null;
        }
        result.class_ = class_.class_;
        result.fixedClass_ = class_.fixedClass_;
        result.extendsClass = class_.extendsClass;
        result.methods = Matcher.getFunctions(code);
        result.classDefine = Matcher.getClassDefine(code);
        return result;
    }
    static defineClass(info) {
        if (!info) {
            throw new Error("info is null");
        }
        let code = `// This ClassDefine is generated by tools/class.ts, generated time: ${getCurrentDate()}\n`;
        code += `ClassDefine<${info.classDefine.class_}> ${info.class_}::builder = \n`;
        code += `\tdefineClass<${info.classDefine.class_}>("${info.fixedClass_}")\n`;
        if (info.classDefine.class_ != "void") {
            code += `\t\t.constructor(nullptr)\n`;
        }
        function genMethods(info, extends_ = false) {
            info.methods.forEach((fn) => {
                if (extends_ && fn.name == "toString") {
                    return; // skip
                }
                if (fn.isStatic) {
                    code += `\t\t.function("${fn.name}", &${info.class_}::${fn.name})\n`;
                }
                else {
                    code += `\t\t.instanceFunction("${fn.name}", &${info.class_}::${fn.name})\n`;
                }
            });
        }
        genMethods(info);
        if (info.extendsClass.length > 0) {
            for (let i = 0; i < info.extendsClass.length; i++) {
                const class_ = info.extendsClass[i];
                const file = findFile(path.join("./src/api"), `${class_.class_}.h`);
                if (file) {
                    const content = fs.readFileSync(path.join("./src/api", file), "utf-8");
                    const result = Generator.collectClassInfo(content);
                    if (result) {
                        code += `\n\t\t\/\/ ${info.class_} extends ${result.class_}\n`;
                        genMethods(result, true);
                    }
                }
            }
        }
        code += `\t\t.build();\n\n`;
        return code;
    }
}
/**
 * 递归查找指定文件，返回相对路径
 * @param dir 开始查找的目录
 * @param file 要查找的文件名
 * @returns 找到文件的相对路径，如果未找到返回 null
 */
function findFile(dir, file) {
    const queue = [dir];
    while (queue.length > 0) {
        const currentDir = queue.shift();
        try {
            const entries = fs.readdirSync(currentDir);
            for (const entry of entries) {
                const fullPath = path.join(currentDir, entry);
                const stats = fs.statSync(fullPath);
                if (stats.isDirectory()) {
                    queue.push(fullPath);
                }
                else if (stats.isFile() && entry === file) {
                    return path.relative(dir, fullPath);
                }
            }
        }
        catch (err) {
            console.error(`Error reading directory ${currentDir}: ${err}`);
        }
    }
    return null;
}
function getCurrentDate() {
    const now = new Date();
    const year = now.getFullYear();
    const month = String(now.getMonth() + 1).padStart(2, "0");
    const day = String(now.getDate()).padStart(2, "0");
    return `${year}-${month}-${day}`;
}
function main(file) {
    let project_dir = process.cwd();
    // 检查当前工作路径是否是在tools目录下，是则则返回上一级目录
    if (path.basename(project_dir) == "tools") {
        project_dir = path.dirname(project_dir);
        process.chdir(project_dir);
    }
    const code = fs.readFileSync(file, "utf-8");
    const result = Generator.collectClassInfo(code);
    if (result) {
        // console.log(JSON.stringify(result, null, 2));
        console.log(Generator.defineClass(result));
    }
}
main(process.argv[2]);
